version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8080
      - FMCSA_API_KEY=cdc33e44d693a3a58451898d4ec9df862c65b954 